version: '3'

services:
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    environment:
      database_client: mysql
      database_connection_database: ghost
      database_connection_host: db
      database_connection_user: root
      database_connection_password: password
    depends_on:
      - 'db'
    networks:
      - my-network

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - my-db:/var/lib/mysql
    networks:
    - my-network

volumes:
  my-db:
  
networks:
  my-network: